[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/contracts/src/v0.8/shared/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[lint]
# ... rest of lint config ...
exclude_lints = ["mixed-case-variable", 
                "unsafe-typecast", 
                "unwrapped-modifier-logic", 
                "mixed-case-function", 
                "screaming-snake-case-immutable", 
                "unaliased-plain-import"]